name: management_app
description: "A comprehensive Flutter management application."

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# Version: follows semantic versioning (major.minor.patch+build)
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  
  # Utilities
  path: ^1.8.3
  intl: ^0.19.0
  
  # Splash Screen
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter native splash configuration
flutter_native_splash:
  color: "#ffffff"
  # image: assets/images/splash_logo.png
  # color_dark: "#000000"
  # image_dark: assets/images/splash_logo_dark.png

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"

  # Fonts (uncomment and customize as needed)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700